version: "3.8"
networks:
  live_in_network:
    driver: bridge
services:
  database:
    container_name: live_in_database
    image: postgres:17
    stdin_open: true
    tty: true
    working_dir: /source
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_DB: live_in_backend
      POSTGRES_USER: pdclab
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - live_in_network

  backend:
    container_name: live_in_backend
    build:
      context: .
      dockerfile: ./dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    # command: python -c "import time; time.sleep(100)"
    # command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    # volumes:
    #   # ./ 這個資料夾掛在 docker image 的 backend 底下
    #   - ./:/backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://pdclab:123456@database:5432/live_in_backend
    depends_on:
      - database
    networks:
      - live_in_network
