version: "3.8"
networks:
  live_in_network:
    driver: bridge
services:
  database:
    container_name: live_in_database
    image: postgres:17
    stdin_open: true
    tty: true
    working_dir: /source
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_DB: live_in_backend
      POSTGRES_USER: pdclab
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - live_in_network

  backend:
    container_name: live_in_backend
    build:
      context: .
      dockerfile: ./dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - live_in_network
